// Command presets writes the preset shapes of DrawingML, from the
// presetShapeDefinitions.xml of ECMA-376 as Apache POI ships it
// (poi/src/main/resources/org/apache/poi/sl/draw/geom), into the list the
// Go package checks names against and the definitions the Dart package
// draws them from.
//
//	go run ./tools/presets presetShapeDefinitions.xml
package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"
	"log"
	"os"
	"slices"

	"github.com/citadellefr/loffice/drawingml"
	"github.com/citadellefr/loffice/internal/xmldom"
)

func main() {
	if len(os.Args) != 2 {
		log.Fatal("usage: presets presetShapeDefinitions.xml")
	}
	data, err := os.ReadFile(os.Args[1])
	if err != nil {
		log.Fatal(err)
	}
	doc, err := xmldom.Parse(data)
	if err != nil {
		log.Fatal(err)
	}
	defs := map[string]json.RawMessage{}
	for _, shape := range doc.Root.Elements() {
		wrapper := xmldom.New(drawingml.NS, "a:custGeom")
		for _, c := range shape.Elements() {
			c.Space = drawingml.NS
			for _, e := range c.Elements() {
				setSpace(e)
			}
			wrapper.Append(c)
		}
		spPr := xmldom.New(drawingml.NS, "a:spPr")
		spPr.Append(wrapper)
		g := drawingml.GeometryIn(spPr)
		if g == nil || g.Custom == nil {
			log.Fatalf("%s: no geometry", shape.Local)
		}
		// an erratum of ECMA-376: the text rectangle of pie has its top and
		// right swapped
		if shape.Local == "pie" && slices.Equal(g.Custom.Rect, []string{"il", "ir", "it", "ib"}) {
			g.Custom.Rect = []string{"il", "it", "ir", "ib"}
		}
		def, err := json.Marshal(g.Custom)
		if err != nil {
			log.Fatal(err)
		}
		defs[shape.Local] = def
	}
	names := make([]string, 0, len(defs))
	for n := range defs {
		names = append(names, n)
	}
	slices.Sort(names)

	var goSrc bytes.Buffer
	goSrc.WriteString("// Code generated by tools/presets. DO NOT EDIT.\n\npackage drawingml\n\n// presets are the names of the preset shapes.\nvar presets = map[string]bool{\n")
	for _, n := range names {
		fmt.Fprintf(&goSrc, "\t%q: true,\n", n)
	}
	goSrc.WriteString("}\n")
	formatted, err := format.Source(goSrc.Bytes())
	if err != nil {
		log.Fatal(err)
	}
	write("drawingml/presets.go", formatted)

	var dart bytes.Buffer
	dart.WriteString("// Generated by tools/presets from the preset shape definitions of ECMA-376.\n// Do not edit.\n\n/// The preset shapes, each a custom geometry as the Go package writes them.\nconst presetGeometries = <String, String>{\n")
	for _, n := range names {
		fmt.Fprintf(&dart, "  '%s': r'%s',\n", n, defs[n])
	}
	dart.WriteString("};\n")
	write("dart/lib/src/drawing/presets.dart", dart.Bytes())
}

func setSpace(e *xmldom.Element) {
	e.Space = drawingml.NS
	for _, c := range e.Elements() {
		setSpace(c)
	}
}

func write(path string, data []byte) {
	if err := os.WriteFile(path, data, 0o644); err != nil {
		log.Fatal(err)
	}
}
